##:import Snackbar kivymd.uix.snackbar.Snackbar
##:import Window kivy.core.window.Window

<MainLayout>:   
    MDBoxLayout:
        orientation: "vertical"
        size: root.size
        MDTopAppBar:
            title: "Navigation Bar"
            left_action_items: [["menu"]]
            right_action_items: [["dots-vertical"],["theme-light-dark"]]
        
        MDBottomNavigation:
            panel_color: app.theme_cls.primary_color
            selected_color_background: None
            text_color_active: app.theme_cls.primary_dark
            text_color_normal: 1,1,1,1
            use_text: False
            

            MDBottomNavigationItem:
                name: 'screen 1'
                icon: 'home-outline'
                #on_tab_press: root.load_cards()
                #badge_icon: "numeric-10"
                
                ScrollView:
                    do_scroll_y: True
                    do_scroll_x: False
                    GridLayout:
                        id: scrn_grid
                        cols: 2
                        padding: '15dp'
                        spacing: '10dp'
                        size_hint_y: None
                        height: self.minimum_height
                        width: self.minimum_width
                        
                                   
            
                        
                         
            MDBottomNavigationItem:
                name: 'screen 2'
                icon: 'magnify'
                #badge_icon: "numeric-10"
                
                ScrollView:
                    do_scroll_y: True
                    do_scroll_x: False
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        padding: 20
                        spacing: 20
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                        MDCard:
                            size_hint_y: None
                            height: "100dp"
                            radius: "15dp"
                            md_bg_color: "#062329"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 15
                                MDIconButton:
                                    icon: "netflix"
                                    icon_size: "64dp"
                                    pos_hint: {'center_y': 0.5}
                                    theme_icon_color: "Custom"
                                    icon_color: "red"
                                MDLabel:
                                    text: "Watch Movies"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
                                MDLabel:
                                    text: "08:30 PM"
                                    halign: "right"
                                    theme_text_color: "Custom"
                                    text_color: "white"
                                    font_size: "25sp"
            MDBottomNavigationItem:
                name: 'screen 3'
                icon: 'plus'
                #badge_icon: "numeric-10"
                
                MDLabel:
                    text: 'Welcome to KivyMD- SECTION 3'
                    halign: 'center'
                    font_size: '55sp'
                    theme_text_color: "Custom"
                    text_color: app.theme_cls.primary_color

            MDBottomNavigationItem:
                name: 'screen 4'
                icon: 'message-processing-outline'
                #badge_icon: "numeric-10"
                ScrollView:
                    do_scroll_y: True
                    do_scroll_x: False
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        padding: 20
                        spacing: 20
                        TwoLineAvatarIconListItem:
                            text: "Spaced out"
                            secondary_text: "Khalil wakes up and finds"

                            ImageLeftWidget:
                                source: "https://picsum.photos/id/46/280/350"

                            IconRightWidget:
                                icon: "menu"
                        TwoLineAvatarIconListItem:
                            text: "House in the Clouds"
                            secondary_text: "Khalil wakes up and finds"

                            ImageLeftWidget:
                                source: "https://picsum.photos/id/56/280/350"

                            IconRightWidget:
                                icon: "menu"

                        TwoLineAvatarIconListItem:
                            text: "Light up the night"
                            secondary_text: "Khalil wakes up and finds"

                            ImageLeftWidget:
                                source: "https://picsum.photos/id/76/280/350"

                            IconRightWidget:
                                icon: "menu"

            MDBottomNavigationItem:
                name: 'screen 5'
                icon: 'bell-outline'
                #badge_icon: "numeric-10"
                
                MDRaisedButton:
                    text: "Create simple snackbar"
                    font_size: "18sp"
                    #on_release: Snackbar(text="This is a snackbar!").open()
                    pos_hint: {"center_x": .5, "center_y": .8}
                    #Snackbar(text="This is a snackbar!",snackbar_x="10dp",snackbar_y="10dp",size_hint_x=(Window.width - (dp(10) * 2)) / Window.width).open()
                MDRaisedButton:
                    text: "Create custom snackbar"
                    font_size: "18sp"
                    #on_release: root.open_custom_snackbar()
                    pos_hint: {"center_x": .5, "center_y": .55}
                
                MDRaisedButton:
                    text: "Create Icon snackbar"
                    font_size: "18sp"
                    #on_release: root.insert_image()
                    pos_hint: {"center_x": .5, "center_y": .3}